server:
  port: 8080

spring:
  servlet:
    multipart:
      max-file-size: 64MB
      max-request-size: 128MB
  thymeleaf:
    cache: false
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: llama3.2:1b
      embedding:
        options:
          model: nomic-embed-text

aion:
  output-dir: ./Output
  documents-dir: ./Documents
  doc-buddy-similarity-threshold: 0.6
  gemini-api-key: ${GEMINI_API_KEY:}
  gemini-model: gemini-1.5-flash
